### PR TITLE
Document regression test steps.

### PR DESCRIPTION
**Pull request by abacaphiliac**
Documents steps necessary to run the regression test suite.

### CODE REVIEW

**Comment by abacaphiliac** [comment]
@leebyron I've been through these steps a few times over the past couple of days, and ran through them just now once more for good measure. It looks right to me. How about you?

**Comment by leebyron** [comment]
Awesome! What do you think about moving this to the `CONTRIBUTING.md` file?

**Comment by abacaphiliac** [comment]
Great idea. Coming up.

**Comment by abacaphiliac** [comment]
@leebyron does that look right?

**Comment by leebyron** [comment]
Looks great! Thanks for your help improving documentation!

**Pull request merged**
