### PR TITLE
bump devDependencies, npm test passed

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
hmmmmm ... it passed the test in local machine only ...

**Comment by PeterDaveHello** [comment]
Test passed!

**Comment by leebyron** [comment]
Thanks, but when patching this in, I'm getting failures when running `grunt` with this patch applied.

**Comment by PeterDaveHello** [comment]
Oh never mind.

**Comment by PeterDaveHello** [comment]
Just leave grunt-jest and typescript alone :+1:

**Comment by leebyron** [comment]
Thanks, this just landed in rebased form!

**Comment by PeterDaveHello** [comment]
didn't see it, never mind.

**Pull request closed without merging**
