### PR TITLE
Make it obvious that a Record is a Map

### PR DESCRIPTION
**Pull request by johnnyreilly**
and so shares the API of Map.  I only discovered this by accident so it seems potentially worth emphasing?

### CODE REVIEW

**Comment by rawls238** [comment]
Given this issue https://github.com/facebook/immutable-js/issues/505 I don't think we want to emphasize this since it should not share an identical API as Map

**Comment by johnnyreilly** [comment]
That's a fair point. That said, the docs don't presently detail how one changes a record (using set, update etc) at all. That should be corrected and guidance given I think.

**Comment by ir-fuel** [comment]
Johnny has a point. Right now the docs only show definition, construction and field removal. I wasn't aware of the other methods until I stumbled upon this issue.

**Comment by leebyron** [comment]
This is actually just an implementation detail, and one that's likely to change in the future. It's a "Map" in the sense that it exposes `get` and `set` methods, but the HOF methods like `filter` and `forEach` make no sense on a Record.

**Pull request closed without merging**
