### PR TITLE
Implementation of Record Lists

### PR DESCRIPTION
**Pull request by Gozala**
This is a fix for #407. Please note that this change is based on #411 so it will appear to contain somewhat unrelated changes actual changes related to only this feature are:
https://github.com/Gozala/immutable-js/compare/sub-records...Gozala:list-record

### CODE REVIEW

**Comment by Gozala** [comment]
For now I just did some manual testing as I'm having issues with running tests locally (see #412 for details) and I need to crash. Will submit actual test for this feature tomorrow.

**Comment by leebyron** [comment]
Considering that Record.List's constructor returns a List. I'm not convinced this warrants being a new type of collection. Instead what it looks like you want to do is build a smarter kind of `fromJS` which is aware of a schema of Records, Lists (and Maps, Sets).

I would recommend re-framing this as a standalone function which takes two arguments: the "shape" of the data to construct and the input js object data that returns a tree of Immutable collections in the appropriate shape.

**Comment by Gozala** [comment]
> Considering that Record.List's constructor returns a List. I'm not convinced this warrants being a new type of collection. Instead what it looks like you want to do is build a smarter kind of fromJS which is aware of a schema of Records, Lists (and Maps, Sets).

That is not entirely correct, `RecordType.List()` returns a subclass of the `List`, which is indeed a List but it's `.push()` `.pop()` etc have different behavior in that they do add instances of `RecordType`. This does enables you to define polymorphic operations over lists that don't need to be `RecordType` specific that this list consists of. In other words parsing JS at the construction is a part of it indeed, but there is more to this than just that.

I do agree though that other types (but Maps) should probably have it as well.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by lacker** [comment]
Hey, I think this pull request has essentially timed out. Sorry! I am going to close it but if you are still interested in it enough to rebase and poke around to see if it still makes sense then please feel free to reopen.

**Pull request closed without merging**
