### PR TITLE
get set intersect working after add or union in withMutations

### PR DESCRIPTION
**Pull request by yetanotherhacker**
This addresses issue #419.

### CODE REVIEW

**Comment by leebyron** [comment]
Hmm, this seems like a mitigation rather than a fix. A map shouldn't have nulled entries like this. Let me dig deeper, but thank you for your initial exploration.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kozlitinaelja** [comment]
@leebyron, is there any decision was made regarding this PR?

**Comment by leebyron** [comment]
I'd like to get to the bottom of this. The original fix is patching a symptom and probably isn't the only place this could appear.

**Pull request closed without merging**
