### PR TITLE
Add [Symbol.iterator] signature to `Iterable.Keyed`, `Iterable.Indexd` & `Iterable.Set`.

### PR DESCRIPTION
**Pull request by Strate**

### CODE REVIEW

**Comment by linusnorton** [comment]
What's happening with this? Does FB accept PRs from outsiders?

**Comment by lacker** [comment]
Yea we do accept PRs. I could use a description of what this PR is all about, the ones with no description I stuck at the bottom of my "to-review" pile

**Comment by linusnorton** [comment]
Description of issue here - https://github.com/facebook/immutable-js/issues/1003

This PR adds the necessary definitions to work with for of loops.

**Comment by leebyron** [comment]
Super dope, thanks. Loving all these new TS features.

**Pull request merged**
