### PR TITLE
add test for calling toJS on results of entrySeq (see #803)

### PR DESCRIPTION
**Pull request by rossipedia**
Failing test for #803

### CODE REVIEW

**Comment by lacker** [comment]
This pull request looks helpful, but would you mind resolving the conflict? Sorry for leaving this for so long unanswered! I'd like to get this in though.

**Comment by rossipedia** [comment]
I forgot all about this! Yeah I can give it a whirl later this evening.

**Comment by lacker** [comment]
Awesome!

**Comment by rossipedia** [comment]
@lacker conflicts resolved!

**Comment by lacker** [comment]
Hmm, this test appears to be failing on Travis: https://travis-ci.org/facebook/immutable-js/builds/184427778

**Comment by rossipedia** [comment]
Oh, I never provided a fix, just a failing test. I brought the initial bug up in #803, and it was requested that I provide a failing test to illustrate the behavior (I think @leebyron asked me via Twitter).

**Comment by rossipedia** [comment]
I'd be happy to provide a fix if I can find the time to dig in. I'm not currently depending on immutablejs at the moment, so it's a bit low priority, so if nobody else can get to it it's not a huge deal.

**Comment by lacker** [comment]
Oh, I see. I thought this test was just like an improvement to the test coverage. My bad

**Pull request closed without merging**
