### PR TITLE
docs(search): add docsearch

### LINKED ISSUE #1501: Add search to the docs
### What happened

I wanted to look something up, but couldn't find exactly what I needed without some probing around. 

### How to solve this

We could add search to the docs, with [DocSearch](https://community.algolia.com/docsearch) this would be quite simple. I'm sure that me and @s-pace would be available to help set it up 🙌 !

### PR DESCRIPTION
**Pull request by Haroenv**
This is the simplest way i found to add it, it can be improved, but I chose to lazy load docsearch; and didn't want to change too much in the css

closes #1501

cc @leebyron, does this what you want? :)

### CODE REVIEW

**Comment by Haroenv** [comment]
Whoops, I just realised I left my debugging br's in there. I'm done with this for today, but maybe it's fine?

**Comment by Haroenv** [comment]
here's how it looks: https://priceless-volhard-23828e.netlify.com/docs/#/

**Comment by Haroenv** [comment]
ping @leebyron, did you get a chance to look at this?

**Comment by leebyron** [comment]
Nice! Looks like we could use a follow up to add some styling so it's more clear that it's a search box, but otherwise looking nice

**Pull request merged**
