### PR TITLE
Fixed display images in mobile version

### PR DESCRIPTION
**Pull request by VladBlow**
In mobile version big image destroyed width layout, I tried to fix this.

### CODE REVIEW

**Comment by VladBlow** [comment]
@leebyron I think the problem is associated with the tests `es-6` and config compiler TypeScript. Just I don't see this config that fixed.

**Comment by leebyron** [comment]
FYI there's no need to close and reopen the PR, other activity also is visible.

Let me take a closer look at this - just from first glance I see the formatting doesn't match the rest of the file. I'll patch locally to make sure this doesn't break any other aspect of the layout

**Comment by leebyron** [comment]
I applied some edits before merging. Thanks for your help!

**Comment by VladBlow** [comment]
@leebyron Thanks!

**Pull request closed without merging**
