### PR TITLE
Fix infinite loop in slice from #459

### PR DESCRIPTION
**Pull request by saromanov**
Hi!
In the Issue #459 was described problem with infinite loop after calling ```slice```.
I found, that this problem not only with List, but with all types, which call function ```wholeSlice``` from the file TrieUtils.js. Infinite loop starts every time when ```slice``` parameters begin or end is not integer
```javascript
var vec = Immutable.List([7,4,5,8]);
result = vec.slice(0,"A");
console.log(result); //infinite loop
//Same thing in console.log(vec.slice(NaN,NaN));
//or console.log(vec.slice("A","B"));
//or result.toJS()
```
I fixed this and now, every time when slice gets non integers parmeters, it returns valid value
```javascript
var vec = Immutable.List([7,4,5,8]);
console.log(vec.slice(0,"A")); //List [7,4,5,8]
```

### CODE REVIEW

**Comment by saromanov** [comment]
Hm, it looks that node v0.10.38 is not supported ```Number.isInteger()```. In the 0.12.4 it forked fine. Of course, it can be replaced with ```Math.round(num) === num ``` or something like this, but it will be not ES6 harmony style :)

**Comment by leebyron** [comment]
To detect NaN you can just do `value !== value`, NaN is the only value which fails that test.

Infinite recursion is bad news, so it would be nice to invariant here, however what I'd love to see is a test that `_capacity` can never become NaN in the first place.

**Comment by saromanov** [comment]
Unfortunately, it looks, what test case probably is not complete in the place. in the ```slice.ts```, checks only case with NaN, but not checks another types(float, string). Detect only NaN is not enough. Also, this problem occurs after toJS method and this case also missed in the ```slice.ts```.
I think, i will provide this test cases and test case with ```__capacity```

**Comment by leebyron** [comment]
Thanks again for this investigation which inspired #511, fixing #459

**Pull request closed without merging**
