### PR TITLE
Add Default Export to Flow Type definitions

### PR DESCRIPTION
**Pull request by ccorcos**
This PR solves this issue:

https://github.com/facebook/immutable-js/issues/854

In the [Flow documentation](https://flowtype.org/docs/third-party.html#example) the show an example where you define library definitions in the `libs` option. So you may be inclined to use these type declarations by having the following in your flowconfig:

```
[libs]
./node_modules/immutable-js/dist/immutable.js.flow
```

The problem with this approach is that those type definitions are now global. Anytime you define a Map type, its going to defer to the Immutable Map and ever the window.Map type definition.

In a [separate part of the documentation](https://flowtype.org/docs/declarations.html#declaration-files) the talk about delcaration files using the `.js.flow` approach. Now instead of adding the files as a global declaration in libs, you can simply `import immutable from 'immutable'` and everything just works :)

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ccorcos** [comment]
Just signed the contributors license agreement

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by ccorcos** [comment]
I also want to mention that it would be great if we could somehow get some strong typing behind Map and List literals. For example, If I have something like `Immutable.toJS({a: 1, b: 'hello'})` where I could define this as a strict schema that can be validated by the type checker rather than everything be nullable generic Maps.

**Comment by lacker** [comment]
Does this PR still make sense now that we merged https://github.com/facebook/immutable-js/pull/878 ?

**Comment by kozlitinaelja** [comment]
@ccorcos, is the issue addressed in this PR still exists? If no, please, close. 😅

**Comment by ccorcos** [comment]
@kozlitinaelja yes -- the definitions are still declared globally. Therefore, you can only have one Map which refers to the immutable Map and not window.Map.

https://flowtype.org/docs/declarations.html#declaration-files

**Comment by leebyron** [comment]
@ccorcos could you recommend a way to test this change that would otherwise currently fail? I just added a flow type test that ensures the native es6 collections can be used alongside the Immutable.js ones.

**Comment by ccorcos** [comment]
Are you doing `import Immutable from 'Immutable'`?

**Comment by sghall** [comment]
In case anyone else lands here.  Doing...

`import * as Immutable from 'immutable`

is a workaround until there's a release that resolves the issue.  That got rid of the flow errors for me.

**Pull request closed without merging**
