### PR TITLE
Typescript: export Immutable as a module

### PR DESCRIPTION
**Pull request by jmalonzo**
This is helpful in cases where immutable.js was imported via a script tag, as "immutable" will not
be available in that environment (but Immutable is).

### CODE REVIEW

**Comment by jmalonzo** [comment]
@leebyron I've updated the comment and squashed the commits. Cheers.

**Comment by leebyron** [comment]
Thanks!

**Comment by leebyron** [comment]
For future reference, once you squash your commits, you can just run `git push -f` to update the same PR without having to make a new one.

**Comment by jmalonzo** [comment]
@leebyron thanks, will do!

**Pull request merged**
