### PR TITLE
test merge and mergeDeep of Map instances with Symbol keys

### PR DESCRIPTION
**Pull request by abacaphiliac**
adds tests to cover merge and mergeDeep of Map instances with Symbols as keys.

### CODE REVIEW

**Comment by abacaphiliac** [comment]
@leebyron Am I crazy, or is this actually working? I think this proves the use-case I described in #1392, with no changes to source. Did something else in master change?

**Comment by leebyron** [comment]
Is it possible that Symbol is getting compiled by typescript to a string?

**Comment by leebyron** [comment]
I can't reproduce this test passing locally, something is fishy

**Comment by abacaphiliac** [comment]
I'm not sure why you and I are seeing different things, but I did throw a couple of `console.log` statements in one of these tests, and this is what came out...

```
  console.log __tests__/merge.ts:224
    Map {}

  console.log __tests__/merge.ts:225
    Map {}
```

I'll make sure the tests I'm running check for specific values at specific key depths without lazily checking object equivalency. These false positives (for me) were definitely under the radar!

**Pull request closed without merging**
