### PR TITLE
Implement sub-record construction / update preserving record types

### PR DESCRIPTION
**Pull request by Gozala**
This is a fix for #408

### CODE REVIEW

**Comment by Gozala** [comment]
Please not I was unable to pass tests on my machine neither with nor without my changes it maybe related to version of node (0.12.0) as I noticed travis is running on older version of it.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kozlitinaelja** [comment]
Hi there. I am starting handling backlog. I know it is been a while since you've submitted PR, sorry for such delay. The are some conflicts. Could you rebase or close the issue is obsolete? 😅

**Comment by leebyron** [comment]
Closing in favor of 44b20e4168613a7d28920495115a741b20fef2b4 for the future major version - though we still need to get type definitions to work correctly.

**Pull request closed without merging**
