### PR TITLE
Update type definitions to match nested Indexed, Keyed, Set variants

### PR DESCRIPTION
**Pull request by matthewwithanm**
Re: #592

### CODE REVIEW

**Comment by myitcv** [comment]
@matthewwithanm - what does the resulting documentation look like (not sure how to regenerate)?

**Comment by matthewwithanm** [comment]
Good question! I hadn't checked /:

The doc generation is in the gh-pages branch and currently chokes on the new file…I've opened #648 to teach the visitor about qualified names. After that, these things look pretty much like you might expect (or at least pretty much like I expect):

# Nav

screen shot 2015-10-03 at 9 16 10 am

# Content

screen shot 2015-10-03 at 9 17 20 am

**Comment by myitcv** [comment]
I'll defer to @leebyron - just so long as the docs (whatever they look like) match the implementation I'm happy :+1:

**Comment by leebyron** [comment]
This is great, thank you for doing this.

**Comment by matthewwithanm** [comment]
😊 np

**Pull request merged**
