### PR TITLE
Add support for `Iterable.splice(n, Infinity)`

### PR DESCRIPTION
**Pull request by joaolucasl**
Previously, `Iterable.splice(n, Infinity)` would return the original `Iterable` itself unchanged. 
This PR adds handling so that `Iterable.splice(n, Infinity)` removes the items accordingly.

One of my first open source PRs, so let me know if I missed something and I'll happily update it :)

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by joaolucasl** [comment]
Oh, just noticed my PR also introduces some style changes (?) but since the lint passed I missed them lol 
Should I update that?

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by lacker** [comment]
As far as I can tell it isn't intended that "Infinity" is supported as a number to pass here. The docs don't claim this works or anything. That seems like it might be nice but at the same time this pull request is pretty old - sorry about that - so I think the practical thing to do here is just to close it. If you're still interested in this please feel free to reopen!

**Pull request closed without merging**
