### PR TITLE
Add transducer protocol to Immutable Data Structures

### PR DESCRIPTION
**Pull request by donabrams**
Completed as per https://github.com/cognitect-labs/transducers-js/issues/20. cc: https://github.com/facebook/immutable-js/issues/538.

I ran some tests locally (see https://gist.github.com/donabrams/3f42e7017170b52593f5), but I was using an implementation (https://github.com/transduce/transduce) to test this rather than some standalone code. I'm not sure what tests would be appropriate to commit here.

### CODE REVIEW

**Comment by leebyron** [comment]
Hey @donabrams let's update this and get it working!

It looks like the transducer protocol suggests that it use symbols when available, should this do the same?

You can look at how Immutable implements the Iterator protocol for an example.

**Comment by donabrams** [comment]
It looks like the double at strings were used at the time, since symbols weren't ready yet. Only Gonzala used symbols:
[`Symbol.for("transducer/step")`](https://github.com/search?utf8=%E2%9C%93&q=%22Symbol.for%28%5C%22transducer%2Fstep%5C%22%29%22&type=Code&ref=searchresults) vs. [`"@@transducer/step"`](https://github.com/search?utf8=%E2%9C%93&q=%22%5C%22%40%40transducer%2Fstep%5C%22%22&type=Code&ref=searchresults)

**Comment by leebyron** [comment]
Ok, we can omit Symbols for now and add them later. This is cool.

Could you please include some simple test cases? That will help ensure these never break in the future, but would also document the minimal use cases.

**Comment by donabrams** [comment]
Yeah, I originally drew a blank when deciding what tests I'd write for this. Since these interfaces are declarative but imply that these data structures hold certain properties, I'd think the right test would be around the property invariants. Really, there should be a generative/invariant test for anyone implementing transducer protocol but I couldn't find one :( I'll update this w/in the next few days.

**Comment by keeth** [comment]
Would love to see this merged.. anything an outsider could do to help move it along?

**Comment by lacker** [comment]
This pull request seems like it has gotten stalled in "needs tests" state, and I theorize it is stuck there indefinitely, so I am going to close it. If someone is interested in working on this then I think it could definitely still be a useful area to work on though.

**Pull request closed without merging**
