### PR TITLE
Update to latest jest version 23.6.0

### PR DESCRIPTION
**Pull request by trivikr**
Fixes: https://github.com/facebook/immutable-js/issues/1620

### CODE REVIEW

**Comment by trivikr** [comment]
Any update on this?

**Comment by leebyron** [comment]
Looks like you forgot to include the yarn lock file which is causing travis to fail, I'll try to merge manually

**Comment by leebyron** [comment]
Merged in 9ea87744446cbbf17fb19ceb1aaa656eae5f4f93

**Comment by trivikr** [comment]
Thanks for merging, but looks like the commit is not linked to my account.

**Comment by leebyron** [comment]
Unfortunately that happens in a manual merge which I had to do because this PR wasn’t passing tests

**Comment by trivikr** [comment]
This is a known issue and have been discussed before (example https://github.com/python/miss-islington/issues/16)
I've created an issue at #1633 to discuss how it can be fixed.

**Pull request closed without merging**
