### PR TITLE
make use of Typescript's tuple notation

### PR DESCRIPTION
**Pull request by jbrownson**
Fixes part of https://github.com/facebook/immutable-js/issues/705

The places I fixed were already documented w/ comments, I searched for "[K," and "(K," and filled in the appropriate stuff. The Iterable stuff wants two arguments to Iterable so I left them commented. I'm not sure what the fix for that is.

This should save you some typing anyway if you plan to do this.

### CODE REVIEW

**Comment by leebyron** [comment]
Stuck on #1074

**Comment by leebyron** [comment]
Thanks!

**Comment by leebyron** [comment]
Unfortunately I had to revert this in aeb9aa4f3f9fc374a08ec8d9695ed0dfd2a72cba since it's still breaking tests. Also, this PR seems to have only altered the compiled files and not the original sources, so other tests weren't triggered.

**Comment by jbrownson** [comment]
Thanks for looking at it. I'm not sure if I'm clear, did I do something wrong or just the infrastructure had a problem?

**Pull request merged**
