### PR TITLE
Record set not throw error anymore for consistency with constructor

### PR DESCRIPTION
**Pull request by Freddy03h**
Following the issue #985
I'm testing this behavior on my project to deal with `merge` and `Record` on a redux store.

The goal is to not throw error when `set`or `merge` unexisting attribut(s) on Record to keep consistency with constructor, but also because it's hard to deal with `merge` for `Record` object.

```js
const MyRecord = Immutable.Record({ foo: null })
const record = new MyRecord({ foo: 5, bar: 10 })

record.toJS() // { foo: 5 }
record.set('bar', 10).toJS() // Error: Cannot set unknown key "bar" on Record
record.merge({ foo: 7, bar: 11 }).toJS() // Error: Cannot set unknown key "bar" on Record
record.remove('bar').toJS() // { foo: 5 }
```

Without this change, it's not easy to set new attributs from a data object. And it's useless to transform the data to `Record` before merging, because merging two `Record` mean only keep the second, without anything from the first.

```js
const MyRecord = Immutable.Record({ foo: null, bar: null })
const record1 = new MyRecord({ foo: 5, bar: 10 })
const record2 = new MyRecord({ foo: 8 })

record1.merge(record2).toJS() // { foo: 8, bar: null }
record2.toJS() // { foo: 8, bar: null }
```

(ps: I don't know why there is so much change in `immutable.js.flow`)

### CODE REVIEW

**Comment by leebyron** [comment]
I think the error with `set` still makes sense. It protects against misuse. The desire to have merge behave similarly to constructor makes sense. It would be great to limit this change to merge.

**Comment by Freddy03h** [comment]
• Why protect against misuse on `set` and `merge` but not on `constructor` and `remove` ?

• Why have a different behavior between `merge` and `set`, when currently, `merge` uses the Record's `set` function because this is the behavior on `Map`. I think having a different behavior between `set` and `merge` has more impact than changing the Record's `set.`

**Comment by leebyron** [comment]
>  Why protect against misuse on set and merge but not on constructor and remove ?

I think `set` and `remove` should have similar behavior and `merge` and `constructor` should have similar behavior.

Specifically, I think it's appropriate for errors to be thrown for misuse of `set` or `remove` because they're indicative of mistaken usage. `record.set('unknownkey', 'value')` would be a no-op and typos would be likely to blame for a difficult to debug issues. However I agree `merge` should work similarly to the constructor and allow for applying a merged set that may contain more keys than the record itself does.

**Comment by leebyron** [comment]
Thinking about this more, I think making a breaking change to `remove` by adding throwing behavior could be inappropriate for the next immediate release and so perhaps dropping the error behavior is a reasonable backup plan - and ideally we can use type checking systems like typescript and flow to detect the sort of accidental misuse of set and remove.

**Pull request merged**
