### PR TITLE
`Immutable.fromJS` bug with no classes objects with custom constructor property

### PR DESCRIPTION
**Pull request by augusto-moura**
As said in #1050, the `Immutable.fromJS` current implementation to plain objects conversion, does not work as expected with objects with a custom `constructor` property. In reality the implementation just returns the same object passed as argument.

I fixed it changing the test for plains objects. Now it tests if the prototype of the object it's the same of `Object.prototype` (if the object has a different prototype it means that it is a class instance). Also, I added some tests cases for the solved problem.

I din't tested the performance impact, it will be more slow than the current implementation for sure.

### CODE REVIEW

**Comment by augusto-moura** [comment]
JSPerf points that the new implementation is about 45% slower compared to the current implementation
Https://jsperf.com/plain-object-predicate

**Comment by leebyron** [comment]
Thanks for investigating this. Ideally we could find a more performant implementation. ~1/2 as fast is a very high cost for this edge case

**Comment by augusto-moura** [comment]
Even that the new implementation is slower than the current one, it is quite fast (in practical terms the difference is just some milliseconds).
The performance test is floating between browsers, but the most modern implementations are really optimized.
JSPerf test: https://jsperf.com/plain-object-check

**Comment by simonkberg** [comment]
Couldn't you check `value.constructor === Object || value.constructor === undefined` first and return early, falling back to checking the prototype only if it returns false? Then you would avoid the additional performance cost for most cases.

**Comment by leebyron** [comment]
@simonkberg yes however there are many cases where `isPlainObject()` is handling the uncommon case and it will be very common for non-plain-objects to fall through and hit the slow path.

@augusto-moura milliseconds matter in aggregate! This function is one called very frequently, so I don't think a 25x slowdown will be acceptable. We need to find another approach with a less punishing performance cost.

**Comment by kozlitinaelja** [comment]
@leebyron , it looks like you fixed it by this commit recently:
https://github.com/facebook/immutable-js/commit/2bff0cf0c13e6ec9f2bbfe2c48aec3740d4f552e

So, now there is no need for this PR

**Comment by leebyron** [comment]
I don't think that rev will fix this particular issue. Objects with custom or other-realm prototypes still are not converted

**Comment by augusto-moura** [comment]
I tested adding a condition for only when the object has a own constructor pass by the proptotype check, so the slow path will only hit when necessary, still 10x slower than the current implementation. Imho, in terms of performance, the "constructor is equal to" it's unbeatable.

JSPerf: https://jsperf.com/plain-object-check/6 (for some reason jsperf messed up with the order of test cases)

**Pull request closed without merging**
