### PR TITLE
Prefer explicit string conversion

### PR DESCRIPTION
**Pull request by dashed**
ES6 Symbols will throw a runtime exception if implicitly coerced into a string.

----

Closes https://github.com/facebook/immutable-js/issues/619

-----

Unsure if this is the right patch.

### CODE REVIEW

**Comment by leebyron** [comment]
Thanks! Sorry for letting this sit - did you verify that this fixes the issue for you?

**Comment by Dashed** [comment]
Yep verified. I probably should've put in a test for it.

**Comment by leebyron** [comment]
I'd like to test this. Could you include a test or use case that fails before this patch and works after?

**Comment by Dashed** [comment]
@leebyron I wasn't quite sure how to test this such that:

```js
Symbol() + ''; // this throws
String(Symbol()); // but this doesn't throw
```

I added a test case that I was working from; but didn't get far. I added a polyfill, core-js, which may be undesirable. 

----

I think an alternative approach to testing would be to mock the String constructor using Jest; but I'm not quite sure how to do this.

**Comment by puradox** [comment]
What's the status of this PR? I'm running into the same problem and would like to see this merged.

**Comment by leebyron** [comment]
Tests look good, just need to rebase and merge. Will get to that shortly.

**Comment by dashed** [comment]
This needs more work. I won't be able to look into it for the next few weeks...

**Comment by puradox** [comment]
@dashed Can you explain what needs more work? I can lend a hand :+1:

**Comment by dashed** [comment]
@puradox https://github.com/facebook/immutable-js/pull/620#issuecomment-166125273

**Comment by dashed** [comment]
Yay! Thanks @leebyron ! 🎉

**Comment by runru** [comment]
Recover my Gmail account reginaladnier50@gmail.com

**Pull request merged**
