### PR TITLE
Add "static" to flow type for OrderedSet<t>

### PR DESCRIPTION
**Pull request by DrewML**
Thank you for the amazing work on this project!

### CODE REVIEW

**Comment by lacker** [comment]
I think this pull request has essentially timed out. If you are still paying attention, I was going to request some sort of test to ensure that this is working properly, but my guess is that this is abandoned. I am going to close it but if someone still actively wants to deal with this then please feel free to reopen it!

**Comment by DrewML** [comment]
@lacker Definitely not abandoned. I also can't re-open the issue since I'm not a maintainer on the project.

Having said that, can you give an example of how the other flow types are being tested? I took a cursory glance and didn't see anything.

**Comment by lacker** [comment]
Hey, I'm glad to hear that this is not abandoned! Sorry for closing this, I'll reopen it. Check out https://github.com/facebook/immutable-js/tree/master/type-definitions/tests - when you run `npm test` it sub-runs `npm type-check` which does a flow check on that directory, so if you add some code that exercises this particular type it'll ensure the type checks are correct.

**Comment by DrewML** [comment]
Thanks @lacker! Must have missed those when I looked before. Will update the PR soon and @ mention you when it's good to go.

**Comment by lacker** [comment]
You didn't miss them, they got merged in pretty recently ;-)

**Comment by howardjing** [comment]
I'm currently working on a PR that wound up addressing this issue while trying to fix the flowtype definitions for `toOrderedMap` and `toOrderedSet`. See https://github.com/facebook/immutable-js/pull/1027

**Comment by DrewML** [comment]
@howardjing Nice! I'll close this one in favor of your changes

**Pull request closed without merging**
