### PR TITLE
Flow: Record: Fix created class types

### PR DESCRIPTION
**Pull request by oreqizer**
Change definition for Record where constructor was specified with 'new'.

### CODE REVIEW

**Comment by oreqizer** [comment]
hmm no feedback, should I change something?

**Comment by ianwcarlson** [comment]
@oreqizer This solution works a lot better for me.  The downside is it requires making a dummy instance of RecordClass for `typeof` to work. Example:
```
import { Record } from 'immutable';

const testRecord = Record({
  foo: '',
  bar: 0,
});

const dummyInstance = testRecord(); // can't use "new" here
const anotherInstance = testRecord();

// can't use typeof testRecord here
const testFunc = (inputRecord: typeof dummyInstance) => null;

testFunc(anotherInstance);
```
Semantically it makes sense that a record class is different than an instance of it, but it makes the code a little awkward.  Still, better than before where I had to create my own intersection type from RecordInstance to get this to work.

I've been trying to come up with a clean solution myself, but haven't so far.

**Comment by gajus** [comment]
Whats stopping this from being released?

It looks like a reasonable approach.

**Comment by kozlitinaelja** [comment]
@leebyron, are you agree with this approach? =)

**Comment by leebyron** [comment]
`new` is generally discouraged across all of Immutable.js - these are factory functions (like `String` or `Number`) and not class constructors. We only use class in flow types where necessary to help flow understand type refinements it otherwise wouldn't understand.

One unfortunate issue with this approach is that while it technically allows you to use `new`, the resulting value is only a class instance and does not also have property types. 

That might be fine, but it's a limitation.

I'm going to amend this PR to also include a `RecordOf` higher-order type which allows you to better type the return of a record factory function call.

**Comment by leebyron** [comment]
Specifically check out https://github.com/facebook/immutable-js/blob/master/type-definitions/tests/record.js#L66-L83 for how this ends up affecting the ability to type Records

**Pull request closed without merging**
