### PR TITLE
added List methods push, pop, unshift, shift to List IndexedCursor

### PR DESCRIPTION
**Pull request by tcoopman**
I tried to add some methods to the Cursor API because they are missing. This solves #346.

I'm not sure if this is the right way to do it, because all other methods extend both KeyedCursorPrototype and IndexedCursorPrototype and this only extends IndexedCursorPrototype. So all feedback is more then welcome!

### CODE REVIEW

**Comment by natew** [comment]
This is big for me, really hinders ability to use of cursors until this is fixed! :+1: :+1:

**Comment by tcoopman** [comment]
@natew If there are other methods that are missing, let me know, I'm happy to implement them too.

**Comment by shivawu** [comment]
wow, this is so great, exactly the things I need. Can't wait for it

**Comment by leebyron** [comment]
Nice work, thanks for your patience!

**Comment by natew** [comment]
I'm not sure how to push regular JS items onto an immutable cursor List, this doesn't work:

```js
immutableStore.push.apply(null, jsarray);
```

I've tried a few variations I keep getting:

```js
Possibly unhandled TypeError: Cannot read property 'updateIn' of undefined
    at updateCursor (webpack:///./~/immutable/contrib/cursor/index.js?:279:37)
```

**Comment by tcoopman** [comment]
@natew can you give a full testcase? Somewhere as a gist or something?

**Pull request merged**
