### PR TITLE
Add a link to chai-immutable for testing purposes

### PR DESCRIPTION
**Pull request by astorije**
Not sure what is the best wording for this, I'll be happy to change it to your liking.

### CODE REVIEW

**Comment by astorije** [comment]
Well, I didn't think I would need to sign the CLA since I added a link to the README, but if a bot gets involved... Voilà, I signed it :-)

**Comment by astorije** [comment]
Anyone? @leebyron? :-)

**Comment by leebyron** [comment]
Ok, lets get that in there :)

**Comment by astorije** [comment]
Yay, awesome, thanks @leebyron! Congrats on the new version!

**Pull request merged**
