### PR TITLE
Added set(value). Fixes #249.

### LINKED ISSUE #249: Cursor.set(value: any): Cursor
Can we have a way to set current value of cursor?

```js
Cursor.set(value: any): Cursor
```

It's similar to `update(updater: (value: any) => any): Cursor`, but with being able to set `undefined`.

### PR DESCRIPTION
**Pull request by geirsagberg**
Closes #249. Uses code from @confiks in https://github.com/facebook/immutable-js/pull/250 comment..

### CODE REVIEW

**Comment by Dashed** [comment]
@geirsagberg This can be refactored to use standard API:

```js
IndexedCursorPrototype.set =
KeyedCursorPrototype.set = function(key, value) {
    return arguments.length === 1 this.setIn([], key) ? this.setIn([key], value);
}
```

**Comment by geirsagberg** [comment]
@Dashed tried your version, test fails with: 

```
Cursor › it can set value of a cursor directly
  - TypeError: Object 1 has no method 'updateIn'
        at /Users/geirsagberg/Projects/immutable-js/contrib/cursor/index.js:148:14
        at updateInDeepMap (/Users/geirsagberg/Projects/immutable-js/dist/immutable.js:2500:22)
        at updateInDeepMap (/Users/geirsagberg/Projects/immutable-js/dist/immutable.js:2509:23)
        at src_Map__Map.updateIn (/Users/geirsagberg/Projects/immutable-js/dist/immutable.js:1816:26)
        at updateCursor (/Users/geirsagberg/Projects/immutable-js/contrib/cursor/index.js:307:38)
        at KeyedCursor.IndexedCursorPrototype.updateIn.KeyedCursorPrototype.updateIn (/Users/geirsagberg/Projects/immutable-js/contrib/cursor/index.js:147:10)
        at KeyedCursor.src_Map__Map.setIn (/Users/geirsagberg/Projects/immutable-js/dist/immutable.js:1794:19)
        at KeyedCursor.IndexedCursorPrototype.set.KeyedCursorPrototype.set (/Users/geirsagberg/Projects/immutable-js/contrib/cursor/index.js:89:40)
        at Spec.<anonymous> (/Users/geirsagberg/Projects/immutable-js/contrib/cursor/__tests__/Cursor.ts:247:20)
        at jasmine.Block.execute (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at jasmine.Queue.start (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2051:8)
        at Spec.jasmine.Spec.execute (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2378:14)
        at jasmine.Queue.next_ (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at onComplete (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2094:18)
        at Spec.jasmine.Spec.finish (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2352:5)
        at null.onComplete (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2379:10)
        at jasmine.Queue.next_ (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2108:14)
        at null._onTimeout (/Users/geirsagberg/Projects/immutable-js/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)```

**Comment by Dashed** [comment]
Ah I see. Nevermind then; I didn't actually test my suggestion.

Your PR works much better. :+1:

**Comment by Dashed** [comment]
I've used cursors a little bit more extensively ever since I've suggested https://github.com/facebook/immutable-js/issues/249.

I think `Cursor.set(value: any): Cursor` doesn't seem to be consistent with the the rest of the API of the immutable library; especially since `Cursor` is to be a transparent type. 

I think `Cursor.update(updater)` is a much better approach.

**Comment by geirsagberg** [comment]
All I know is that it feels really unnecessary to do `cursor.update(function() { return newValue; })` if `cursor.set(newValue)` would do the same thing. `cursor.setIn([], newValue)` is slightly better, but is not more intuitive nor easier to read, IMHO.

Can't we add `.set(value)` just for the sugar?

**Comment by geirsagberg** [comment]
Or at least point out a scenario where `.set(value)` would cause undesirable effects, because I can't think of any off the top of my head.

**Comment by Dashed** [comment]
@geirsagberg I totally understand the need; and there isn't anything wrong with the implementation of `Cursor.set(value)` as it is done through this PR.

I'm merely respecting the author's intent of `Cursors` as he has stated here: https://github.com/facebook/immutable-js/issues/242#issuecomment-67198651
Which to me, means the Cursor API should be consistent with the other Immutable collections.

**Comment by leebyron** [comment]
This is reasonable, I understand that it's something people want to use Cursors to do.

**Pull request merged**
